apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1.sho.k8s.io
spec:
  insecureSkipTLSVerify: true
  group: sho.k8s.io
  groupPriorityMinimum: 1000
  versionPriority: 15
  service:
    name: api
    namespace: sho
  version: v1
