apiVersion: v1
kind: ReplicationController
metadata:
  name: sho-server
  namespace: sho
  labels:
    apiserver: "true"
spec:
  replicas: 1
  selector:
    apiserver: "true"
  template:
    metadata:
      labels:
        apiserver: "true"
    spec:
      serviceAccountName: apiserver
      containers:
      - name: sho-server
        image: sanjid/ksd:latest
        imagePullPolicy: Always
        command: ["/ksd", "run", "--etcd-servers=http://localhost:2379" ]
      - name: etcd
        image: quay.io/coreos/etcd:v3.2.16
