/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This file was automatically generated by informer-gen

package v1

import (
	sho_v1 "github.com/sanjid133/ksd/apis/sho/v1"
	versioned "github.com/sanjid133/ksd/client/clientset/versioned"
	internalinterfaces "github.com/sanjid133/ksd/client/informers/externalversions/internalinterfaces"
	v1 "github.com/sanjid133/ksd/client/listers/sho/v1"
	meta_v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// KsdInformer provides access to a shared informer and lister for
// Ksds.
type KsdInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1.KsdLister
}

type ksdInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewKsdInformer constructs a new informer for Ksd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewKsdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredKsdInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredKsdInformer constructs a new informer for Ksd type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredKsdInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options meta_v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShoV1().Ksds(namespace).List(options)
			},
			WatchFunc: func(options meta_v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.ShoV1().Ksds(namespace).Watch(options)
			},
		},
		&sho_v1.Ksd{},
		resyncPeriod,
		indexers,
	)
}

func (f *ksdInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredKsdInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *ksdInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&sho_v1.Ksd{}, f.defaultInformer)
}

func (f *ksdInformer) Lister() v1.KsdLister {
	return v1.NewKsdLister(f.Informer().GetIndexer())
}
